/*
 * This file is generated by jOOQ.
 */
package com.xpeter.model;


import com.xpeter.model.tables.Customer;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Asm extends SchemaImpl {

    private static final long serialVersionUID = -1760224302;

    /**
     * The reference instance of <code>ASM</code>
     */
    public static final Asm ASM = new Asm();

    /**
     * The table <code>ASM.CUSTOMER</code>.
     */
    public final Customer CUSTOMER = Customer.CUSTOMER;

    /**
     * No further instances allowed
     */
    private Asm() {
        super("ASM", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Customer.CUSTOMER);
    }
}
