/*
 * This file is generated by jOOQ.
 */
package com.xpeter.model;


import com.xpeter.model.tables.Customer;


/**
 * Convenience access to all tables in ASM
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>ASM.CUSTOMER</code>.
     */
    public static final Customer CUSTOMER = Customer.CUSTOMER;
}
